### Save all bounds from tiff files

In [1]:
from osgeo import gdal
import rasterio
import numpy as np
import matplotlib as plt
from rasterio.plot import show
import pandas as pd
import georasters as gr
import geopandas as gpd
from matplotlib import pyplot as plt

#### DSM bounds

In [2]:
# DSM bounds from all DSM bounds
data = []

for num in range(1, 43+1):
    
    dataset = rasterio.open(r"Data/DSM/DSM-"+str(num)+"/GeoTIFF/DHMVIIDSMRAS1m_k"+("0" if num <= 9 else "")+str(num)+".tif")
    #data_list = {}
    #for data in data_list:
    data_contents = dataset.bounds
    data.append(data_contents)
    df = pd.DataFrame(data)
df
df.to_csv('ALL_BOUNDS.csv')

In [3]:
dataset.bounds

BoundingBox(left=258000.0, bottom=151000.0, right=264000.0, top=158000.0)

#### DTM bounds

In [5]:
# DTM bounds from all DTM bounds, DSM & DTM bounds are exactly the same.
data = []

for num in range(1, 43+1):
    
    dataset = rasterio.open(r"Data/DTM/DTM-"+str(num)+"/GeoTIFF/DHMVIIDTMRAS1m_k"+("0" if num <= 9 else "")+str(num)+".tif")
   
    data_contents = dataset.bounds
    data.append(data_contents)
    dataframe_DTM = pd.DataFrame(data)
dataframe_DTM

        left    bottom     right       top
0   145000.0  238000.0  162000.0  247000.0
1   162000.0  238000.0  194000.0  250000.0
2   194000.0  238000.0  206000.0  248000.0
3    53000.0  218000.0   66000.0  225500.0
4    66000.0  218000.0   98000.0  232000.0
5    98000.0  218000.0  130000.0  227000.0
6   130000.0  218000.0  162000.0  238000.0
7   162000.0  218000.0  194000.0  238000.0
8   194000.0  218000.0  226000.0  238000.0
9   226000.0  218000.0  238000.0  227000.0
10   18500.0  198000.0   34000.0  206500.0
11   34000.0  198000.0   66000.0  218000.0
12   66000.0  198000.0   98000.0  218000.0
13   98000.0  198000.0  130000.0  218000.0
14  130000.0  198000.0  162000.0  218000.0
15  162000.0  198000.0  194000.0  218000.0
16  194000.0  198000.0  226000.0  218000.0
17  226000.0  198000.0  258000.0  218000.0
18   17000.0  178000.0   34000.0  198000.0
19   34000.0  178000.0   66000.0  198000.0
20   66000.0  178000.0   98000.0  198000.0
21   98000.0  178000.0  130000.0  198000.0
22  130000.0  178000.0  162000.0  198000.0
23  162000.0  178000.0  194000.0  198000.0
24  194000.0  178000.0  226000.0  198000.0
25  226000.0  178000.0  258000.0  198000.0
26   20000.0  158000.0   34000.0  178000.0
27   34000.0  158000.0   66000.0  178000.0
28   66000.0  158000.0   98000.0  178000.0
29   98000.0  158000.0  130000.0  178000.0
30  130000.0  158000.0  162000.0  178000.0
31  162000.0  158000.0  194000.0  178000.0
32  194000.0  158000.0  226000.0  178000.0
33  226000.0  158000.0  258000.0  178000.0
34  258000.0  158000.0  264000.0  169000.0
35   34000.0  151000.0   66000.0  158000.0
36   66000.0  150000.0   98000.0  158000.0
37   98000.0  148000.0  130000.0  158000.0
38  130000.0  148000.0  162000.0  158000.0
39  162000.0  152000.0  194000.0  158000.0
40  194000.0  149000.0  226000.0  158000.0
41  226000.0  151000.0  258000.0  158000.0
42  258000.0  151000.0  264000.0  158000.0